### ISSUE TITLE
XCode 14.3 and new architecture not working

### ISSUE THREAD

**Issue by Rohphi** [mkuczera/react-native-haptic-feedback#100]
on build the error 
'value' is unavailable: introduced in iOS 12.0
is shown

the podfile needs to be adapted to
`s.platform= :ios, "12.4"`

**Comment by mkuczera** [comment]
Fixed in 2.1.0, currently in beta to test it

**Comment by mkuczera** [comment]
Fixed in Release 2.1.0 / 2.2.0
I deprecated the failure releases. Sorry for the issues.
