### ISSUE TITLE
Not work on newest iPhone with iOS above 16.0.0

### ISSUE THREAD

**Issue by caturadjiprasetyo** [mkuczera/react-native-haptic-feedback#101]
it doesn't work on newest iPhone with iOS above 16.0.0

**Comment by caturadjiprasetyo** [comment]
![MicrosoftTeams-image (1)](https://github.com/mkuczera/react-native-haptic-feedback/assets/127071715/ed71240a-05e2-4dfb-9063-065e5e85ca8c)
Already enable vibration

**Comment by lpatrun** [comment]
@caturadjiprasetyo It is under "Sounds & Haptics" menu, at the bottom is "System Haptics" option

**Comment by caturadjiprasetyo** [comment]
It worked, thank you so much @lpatrun
