### ISSUE TITLE
Support haptic feedback for Xiaomi Phone instead of  vibration.

### ISSUE THREAD

**Issue by zhenweiwang1990** [mkuczera/react-native-haptic-feedback#119]

**Comment by kesha-antonov** [comment]
+1

**Comment by CyrusCymmetri** [comment]
Haptic feedback works on my Xiaomi 11T Pro MIUI 14.0.4 - Android 13

Not sure perhaps by default haptics are disabled on Xiaomi phones

**Comment by mkuczera** [comment]
Closing this. If there is an update, please feel free to open a corresponding issue or PR
