### ISSUE TITLE
no feedback on iOS with new version

### ISSUE THREAD

**Issue by alexichristakis** [mkuczera/react-native-haptic-feedback#13]
Used to work perfectly, but now there is no haptic feedback on iPhone X running iOS 11.3. Adding the boolean argument "true" results in the heavy vibration. 

No vibration can be produced otherwise.

**Comment by mkuczera** [comment]
Hey,
which version are you using? I just created a fresh project with 1.1.5 and everything is working fine.
Greetings

**Comment by alexichristakis** [comment]
I'm also using 1.1.5. I've tried reinstalling the package, but haven't tried installing on a fresh project.

**Comment by wouterds** [comment]
Seems to be working here, I'm on the latest iOS version (also using iPhone X).

**Comment by mkuczera** [comment]
Hi, sorry, just looked up and saw that for some reasons 1.1.6 is including the playground instance that i was working on on a different branch. will clean this up today.
Regarding the issue: tested it out with 1.1.5. Everything works fine for me. @alexichristakis can you check if the iPhoneX again? Can not reproduce the bug with 1.1.5

**Comment by alexichristakis** [comment]
I think it was a conflict with another package or a corrupted Xcode project. I started a new RN project and have been reinstalling my dependices without issue. Thanks for the response!
