### ISSUE TITLE
Xcode build failed with errors

### ISSUE THREAD

**Issue by RoyRao2333** [mkuczera/react-native-haptic-feedback#132]
`react-native-haptic-feedback@2.3.1` and `react-native@0.74.2` with `Xcode 15.4`

After pod install, I got these errors when build using Xcode:

<img width="2030" alt="image" src="https://github.com/user-attachments/assets/e73a732d-551e-43fe-aec4-de1cb6c7a59b">

If I follow [Manual Setup Guide - iOS](https://github.com/mkuczera/react-native-haptic-feedback?tab=readme-ov-file#manual-setup-guide---ios), I got:

<img width="2026" alt="image" src="https://github.com/user-attachments/assets/9efc9264-34f2-4a9c-8027-9b4cffde07ad">

I tried to delete DerivedData and reinstall pods, but no luck.

**Comment by ben-upaged** [comment]
I get the same error: "'React/RCTBridgeModule.h' file not found".

Also using the same Xcode 15.4, react-native-haptic-feedback 2.3.1, and react-native 0.74.2

**Comment by llr101** [comment]
same error with 0.75.0-rc.7

**Comment by bogrees** [comment]
same error with 0.75.2, any idea how to fix this?

**Comment by ajiehatajie** [comment]
sames issue

**Comment by bogrees** [comment]
A little more info on this, it's related to having the New Architecture enabled in iOS..

`ENV['RCT_NEW_ARCH_ENABLED'] = '1'` in the Podfile

**Comment by huextrat** [comment]
New arch on RN 0.75.2 is also on failure when building iOS

**Comment by WoLewicki** [comment]
Can you check if https://github.com/mkuczera/react-native-haptic-feedback/pull/133 fixes the problem?

**Comment by huextrat** [comment]
@WoLewicki I've just tried a patch and it seems to work (at least iOS is building now)

**Comment by sambarneyrailspire** [comment]
> A little more info on this, the build error occurs with the New Architecture enabled in iOS.. set that to 0, and it will build, not ideal tho.
> 
> `ENV['RCT_NEW_ARCH_ENABLED'] = '1'` in the Podfile --> causes build error

this solution === if the tires on your truck aren't working because their the wrong size, just don't drive the truck.

**Comment by akindoju** [comment]
Hey, What patch? @huextrat

**Comment by losh11** [comment]
Would really appreciate if we could get a new release soon :)

**Comment by mkuczera** [comment]
Released as v2.3.2 . Sorry, didn´t have time before
