### ISSUE TITLE
License file in repo?

### ISSUE THREAD

**Issue by MattFoley** [mkuczera/react-native-haptic-feedback#14]
Hi,

Would you mind adding an MIT license file into the body of this repository? Your NPM registry and package.json declare it as MIT licensed, but I don't see one in the repository, and I don't think I can use this code base without that. I think Github has a button on the repo settings to do that for you.

Thanks!

**Comment by mkuczera** [comment]
Hey, thanks for the feedback. I added the corresponding LICENCE file.

**Comment by MattFoley** [comment]
Thank you!
