### ISSUE TITLE
Error at bundling before release

### ISSUE THREAD

**Issue by SokWonJeremyKim** [mkuczera/react-native-haptic-feedback#30]
Environment:
React-Native: 0.57.7
OS: MacOS

How to reproduce:
Run the following script:
```
react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
```

Log:
node_modules/react-native-haptic-feedback/index.js: Unexpected token (22:19)

>22 | const triggerHaptic(type, options) {
                                           ^
  23 |     try {
  24 |         NativeModules.RNReactNativeHapticFeedback.trigger(type, options);
  25 |     } catch (err) {

**Comment by mkuczera** [comment]
resolved in version 1.7.1
