### ISSUE TITLE
In Samsung Galaxy phones not work

### ISSUE THREAD

**Issue by dharmrajacharya** [mkuczera/react-native-haptic-feedback#46]
That's working and confirmed on Nexus/Pixel phones, some Huawei, etc, but isn't working for Samsung Galaxy phones and we should cover this segment.

**Comment by panda0603** [comment]
same here. Maybe we should figure out why for certain brands this doesn't work

**Comment by fawazahmed-makeen** [comment]
Try imapctMedium and above:

```
const hapticOptions = {
  enableVibrateFallback: false,
  ignoreAndroidSystemSettings: true,
};

const hapticTriggerType = Platform.select({
  ios: 'selection',
  android: 'impactMedium'
});

ReactNativeHapticFeedback.trigger(hapticTriggerType, hapticOptions)
```

**Comment by Bardiamist** [comment]
Faced with it

**Comment by SebinLee** [comment]
@fawazahmed-makeen It works on Galaxy Devices. Thanks.
