### ISSUE TITLE
'impactLight' no effect on iPhones 6S

### ISSUE THREAD

**Issue by wmonecke** [mkuczera/react-native-haptic-feedback#47]
Hi!

I tested the package and only 'selection' and 'impactMedium' have any effect whatsoever.
Is this because the phone does not support lighter vibrations?

Thank you very much in advance!

**Comment by plaa** [comment]
[The code has condition](https://github.com/junina-de/react-native-haptic-feedback/blob/master/ios/RNReactNativeHapticFeedback.m#L50) that on iPhone 6 & 6S it uses `AudioServicesPlaySystemSound` and handles only the values `selection`, `impactMedium` and `notificationWarning`.

The code should be changed to perform a best-guess mapping from the other constants to the three vibration types allowed on those devices.

**Comment by mkuczera** [comment]
Thanks. I will implement the mapping with the next version and document the corresponding fallbacks

**Comment by WesleyAC** [comment]
It looks like the default fallback for unsupported types on more recent iPhone versions is `selection`, is the plan for the 6s / 6s Plus to also fall back to `selection` as well? That would be quite nice :)

**Comment by haleyngonadi** [comment]
Just confirming this issue on my end as well. Any updates? :)

**Comment by Romick2005** [comment]
I guess we need to have some default feedback for iPhone 6s and iPhone 6s Plus
![image](https://user-images.githubusercontent.com/17779660/174538781-bb0cf90e-9e16-4eef-b0cf-9de72742ca72.png)
