### ISSUE TITLE
Detect haptics?

### ISSUE THREAD

**Issue by jacdx** [mkuczera/react-native-haptic-feedback#58]
Is there a way to detect if your device has haptics? Getting a persistent warning on Simulator when using this library which I would like to avoid.

**Comment by nickmcmillan** [comment]
Possibly related; I'd like to offer the user the option to enable/disable haptics. But I'd only like to show this toggle in the UI if their device actually supports haptics. 

So I'm wondering if there's currently a way to detect if the device supports haptics?

**Comment by mkuczera** [comment]
I´m so sorry. The library just remained a while and i lost track. Did you find a solution for this condition? @nickmcmillan

**Comment by nickmcmillan** [comment]
@mkuczera no I didn't end up solving it. It'd still be a nice to have though.
