### ISSUE TITLE
[iOs] haptic feedback does not working if mic on

### ISSUE THREAD

**Issue by ysimoo** [mkuczera/react-native-haptic-feedback#71]
Hello,

Is there any solution to use haptic feedback when mic is active on iOs ?

React-Native: 0.63.4
expo: 42.0.1

`const options = {
  enableVibrateFallback: true,
  ignoreAndroidSystemSettings: false,
};

ReactNativeHapticFeedback.trigger("selection", options);
`

Thanks,

**Comment by mkuczera** [comment]
Will check for the circumstance

**Comment by jforaker** [comment]
I had the same experience using in conjunction with `react-native-audio-recorder-player`, and found that wrapping my record function in a setTimeout resolved the issue:

```js
            ReactNativeHapticFeedback.trigger('impactHeavy');

            setTimeout(() => {
              startRecording();
            });
```

**Comment by a-vikor** [comment]
In short: can be enabled, read below.

Natively on iOS haptic feedback is disabled during audio recording sessions not to interrupt it. Still, you can enable with 

`
if #available(iOS 13, *) {
                do {
                    try AVAudioSession.sharedInstance().setAllowHapticsAndSystemSoundsDuringRecording(true)
                } catch {}
            }
`
inside the startRecording function of native RNAudioRecorderPlayer.swift file.
